services:
  i2pd:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: i2pd
    volumes:
      - $PWD/data:/app/data
    # ports:
    #   - 127.0.0.1:8888:8888
    #   - 127.0.0.1:7070:7070
    tty: true
    network_mode: host
    restart: unless-stopped
